# Generated by Django 5.0.3 on 2024-03-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='time',
            options={'ordering': ['date', 'start_time']},
        ),
    ]
