# Generated by Django 5.0.3 on 2024-04-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_alter_time_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
