# Generated by Django 5.0.3 on 2024-04-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0003_alter_time_end_time_alter_time_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
