# Generated by Django 5.0.3 on 2024-04-03 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0004_alter_time_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time_duration',
        ),
    ]
