

# 1. Set Trigger
name: CI
on: [push]


# 2. Add Steps to Run test & Linting
jobs:
    test-and-lint:
        name: Test and Lint
        runs-on: ubuntu-latest
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Checkout
            uses: actions/checkout@v2
          - name: Test
            run: docker-compose run --rm backend sh -c "cd backend  && python manage.py test"
          - name: Lint
            run: docker-compose run --rm backend sh -c "flake8"